import forms from "@tailwindcss/forms";

export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9f9",
        error: "#ba1a1a",
        "surface-variant": "#e2e2e2",
        "inverse-on-surface": "#f1f1f1",
        secondary: "#45655b",
        "error-container": "#ffdad6",
        "on-secondary-container": "#4b6b61",
        outline: "#747878",
        "surface-container": "#eeeeee",
        "on-tertiary-fixed": "#2c1600",
        "on-secondary-fixed": "#002019",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3131",
        "on-background": "#1a1c1c",
        "on-tertiary-fixed-variant": "#5f4021",
        "tertiary-fixed-dim": "#ebbe95",
        "on-secondary": "#ffffff",
        background: "#f9f9f9",
        "on-surface-variant": "#444748",
        "surface-tint": "#5f5e5e",
        "on-primary-container": "#959494",
        "on-tertiary-container": "#b58d67",
        "surface-dim": "#dadada",
        "on-tertiary": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container-high": "#e8e8e8",
        "primary-fixed-dim": "#c8c6c6",
        "secondary-fixed-dim": "#accec2",
        "on-primary-fixed-variant": "#474747",
        "surface-container-highest": "#e2e2e2",
        "tertiary-container": "#422709",
        "inverse-primary": "#c8c6c6",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2d2d2d",
        "tertiary-fixed": "#ffdcbe",
        "on-primary-fixed": "#1b1c1c",
        "primary-fixed": "#e4e2e1",
        surface: "#f9f9f9",
        tertiary: "#281400",
        primary: "#181919",
        "on-error-container": "#93000a",
        "on-surface": "#1a1c1c",
        "secondary-fixed": "#c7eade",
        "on-secondary-fixed-variant": "#2e4d44",
        "secondary-container": "#c7eade",
        "outline-variant": "#c4c7c7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        gutter: "24px",
        "container-max-width": "1280px",
      },
      maxWidth: {
        "container-max-width": "1280px",
      },
      fontFamily: {
        "headline-lg": ["Playfair Display"],
        "body-md": ["Montserrat"],
        "display-lg-mobile": ["Playfair Display"],
        "body-lg": ["Montserrat"],
        "label-caps": ["Montserrat"],
        "headline-md": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.5", letterSpacing: "0.15em", fontWeight: "700" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [forms],
};
